In [1]:
import numpy as np
import pandas as pd

# np.save('data.npy', num_arr) # save
# new_num_arr = np.load('data.npy') # load
df = pd.read_csv('american_football_contact.csv')

In [2]:
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

In [3]:
df.head()

game_play  step  nfl_player_id_1  nfl_player_id_2  contact team_1  \
0  58172_003247   120            39109            46273        0   away   
1  58224_003139     0            43324            52453        0   away   
2  58504_002631    30            39950            43341        0   away   
3  58552_000100     0            33084            43313        0   home   
4  58548_003091    60            46211            47885        0   away   

   jersey_number1  x_position_1  y_position_1  speed_1  ...  direction_2  \
0              85         35.81          2.85     2.33  ...       119.67   
1              86         83.55         24.82     0.00  ...       332.80   
2              65         70.63         33.70     3.98  ...       179.60   
3               2         76.65         23.85     0.08  ...       329.60   
4               2         29.38          5.98     0.40  ...       113.83   

   orientation_2  acceleration_2  sa_2      view player_label  left  width  \
0         146.29            1.06 -0.72  Sideline          V85   601     18   
1          76.85            0.13 -0.13   Endzone          V86  1021     24   
2          93.97            2.75  2.75   Endzone          V65   368     24   
3         355.94            3.71  3.60   Endzone           H2   634     24   
4          79.72            1.16  0.39  Sideline           V2   429     12   

   top  height  
0  317      24  
1  349      35  
2  222      23  
3  272      34  
4  426      12  

[5 rows x 31 columns]

In [4]:
df

game_play  step  nfl_player_id_1  nfl_player_id_2  contact team_1  \
0      58172_003247   120            39109            46273        0   away   
1      58224_003139     0            43324            52453        0   away   
2      58504_002631    30            39950            43341        0   away   
3      58552_000100     0            33084            43313        0   home   
4      58548_003091    60            46211            47885        0   away   
...             ...   ...              ...              ...      ...    ...   
18789  58582_003121    30            41222            43296        1   home   
18790  58582_003121    40            46121            48220        1   away   
18791  58582_003121    40            46121            48220        1   away   
18792  58582_003121    40            45009            46284        1   away   
18793  58582_003121    40            45009            46284        1   away   

       jersey_number1  x_position_1  y_position_1  speed_1  ...  direction_2  \
0                  85         35.81          2.85     2.33  ...       119.67   
1                  86         83.55         24.82     0.00  ...       332.80   
2                  65         70.63         33.70     3.98  ...       179.60   
3                   2         76.65         23.85     0.08  ...       329.60   
4                   2         29.38          5.98     0.40  ...       113.83   
...               ...           ...           ...      ...  ...          ...   
18789              78         23.71         27.87     2.42  ...       293.32   
18790              57         25.26         22.06     2.11  ...        24.14   
18791              57         25.26         22.06     2.11  ...        24.14   
18792              97         27.27         24.42     1.52  ...         8.94   
18793              97         27.27         24.42     1.52  ...         8.94   

       orientation_2  acceleration_2  sa_2      view player_label  left  \
0             146.29            1.06 -0.72  Sideline          V85   601   
1              76.85            0.13 -0.13   Endzone          V86  1021   
2              93.97            2.75  2.75   Endzone          V65   368   
3             355.94            3.71  3.60   Endzone           H2   634   
4              79.72            1.16  0.39  Sideline           V2   429   
...              ...             ...   ...       ...          ...   ...   
18789         186.68            3.70 -3.66  Sideline          H78   283   
18790         114.78            1.94 -1.93   Endzone          V57   150   
18791         114.78            1.94 -1.93  Sideline          V57   249   
18792          27.59            1.50 -1.16   Endzone          V97   291   
18793          27.59            1.50 -1.16  Sideline          V97   308   

       width  top  height  
0         18  317      24  
1         24  349      35  
2         24  222      23  
3         24  272      34  
4         12  426      12  
...      ...  ...     ...  
18789     10  273      10  
18790     29  108      27  
18791      9  326       9  
18792     30  156      26  
18793      8  313       8  

[18794 rows x 31 columns]

In [6]:
import os
import cv2
import matplotlib.pyplot as plt
img_arr = []
game_plays =  []
views = []
steps = []
player_labels = []
contact = []
counter = 0
for name in os.listdir('contact/contact_0'):
#     print(name)
    img = cv2.imread(os.path.join('contact/contact_0' ,name),0)
    name = name.replace('.jpg','')
    l = name.split('_')
    game_plays.append('_'.join(l[:2]))
    views.append(l[2])
    steps.append(int(l[3]))
    player_labels.append(l[4])
    contact.append(0)
#     print(img.shape)
    img_resized = cv2.resize(img,(150,150))
    img_arr.append(img_resized.flatten())
#     plt.imshow(img_resized)
#     plt.show()
#     if counter == 0:
#         break
#     counter += 1

In [7]:
len(player_labels)

9980

In [8]:
for name in os.listdir('contact/contact_1'):
#     print(name)
    img = cv2.imread(os.path.join('contact/contact_1' ,name),0)
    name = name.replace('.jpg','')
    l = name.split('_')
    game_plays.append('_'.join(l[:2]))
    views.append(l[2])
    steps.append(int(l[3]))
    player_labels.append(l[4])
    contact.append(1)
#     print(img.shape)
    img_resized = cv2.resize(img,(150,150))
    img_arr.append(img_resized.flatten())

In [9]:
len(img_arr)

18794

In [13]:
flat_data = np.array(img_arr)
contact = np.array(contact)
img_frame = pd.DataFrame(flat_data)
img_frame['contact'] = contact

In [14]:
x = img_frame.iloc[:,:-1]
y = img_frame['contact']

In [15]:
from sklearn import svm
# from sklearn.model_selection import GridSearchCV
# param_grid={'C':[0.1,1,10,100],'gamma':[0.0001,0.001,0.1,1],'kernel':['rbf','poly']}
model = svm.SVC(probability=True, max_iter=200, gamma=0.1)
#model=svm.SVC(probability=True,max_iter = 100)
# model=GridSearchCV(svc,param_grid)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=77,stratify=y)
print('Splitted Successfully')
model.fit(x_train,y_train)
print('The Model is trained well with the given images')
# model.best_params_ contains the best parameters obtained from GridSearchCV

Splitted Successfully
The Model is trained well with the given images


/Users/zainaamir/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:284: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


In [17]:
from sklearn.metrics import accuracy_score
y_pred=model.predict(x_test)
print("The predicted Data is :")
print(y_pred)
print("The actual data is:")
print(np.array(y_test))
print(f"The model is {accuracy_score(y_pred,y_test)*100}% accurate")

The predicted Data is :
[1 1 1 ... 1 1 1]
The actual data is:
[0 0 0 ... 0 1 1]
The model is 47.007182761372704% accurate


In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.67      0.00      0.01      1996
           1       0.47      1.00      0.64      1763

    accuracy                           0.47      3759
   macro avg       0.57      0.50      0.32      3759
weighted avg       0.57      0.47      0.30      3759



In [19]:
from sklearn.metrics import accuracy_score
y_pred=model.predict(x_train)
print("The predicted Data is :")
print(y_pred)
print("The actual data is:")
print(np.array(y_train))
print(f"The model is {accuracy_score(y_pred,y_train)*100}% accurate")

The predicted Data is :
[1 1 1 ... 0 1 0]
The actual data is:
[1 1 1 ... 0 0 0]
The model is 48.027934818756236% accurate
